### ISSUE TITLE
(wixtoolset) support version 3.10.4

### ISSUE THREAD

**Issue by pjljvandelaar** [chocolatey-community/chocolatey-coreteampackages#1071]
On https://github.com/wixtoolset/wix3/releases/tag/wix3104rtm 
is stated:
```
WiX v3.10.4 is the latest recommended maintenance release of WiX v3.10; it contains the mitigations in WiX v3.10.3 for a vulnerability affecting all bundles. We strongly recommend upgrading to WiX v3.10.4 so you can ship safe bundles.
```

On https://chocolatey.org/packages/wixtoolset/3.10.3.3007
there is a list of version of wixtoolset which is supported by Chocolatey.
Yet, 3.10.4(.4718) is not supported.
I would like that version 3.10.4 is also supported

I raised a question there, and was asked by Gary Ewan Park to submit an issue here for further discussion.

**Comment by pjljvandelaar** [comment]
For us no longer relevant since we moved to the latest version of Wix.

**Comment by AdmiringWorm** [comment]
When this issue was opened, it was not possible for us to implement support for this.
However, now there the possibility exist, but there is a need to change the package to use 'streams' to be able to do this.

Personally, I have no incentive to make this happen, but if there is anyone out there that wish to look into this, then feel free to do so.

We are *almost* always available in our gitter channel if you need help. (https://gitter.im/chocolatey/chocolatey-coreteampackages)

**Comment by majkinetor** [comment]
I will close this as it is no longer relevant.
