### ISSUE TITLE
(classic-shell) Renamed to Open-Shell

### ISSUE THREAD

**Issue by mstick99** [chocolatey-community/chocolatey-coreteampackages#1092]
Classic Shell no longer in development as Classic Shell. (See news section at http://www.classicshell.net/) Has been renamed Open Shell and development can now be followed at https://github.com/Open-Shell

**Comment by AdmiringWorm** [comment]
hmm, looked a little into this one now.

I see that the Open-Shell fork haven't yet published a stable release (with binaries), as such deprecating the classic shell package in favor of open shell won't be done until one is available.

**Comment by jarlave** [comment]
Since 4 days there is now an release https://github.com/Open-Shell/Open-Shell-Menu/releases/tag/v4.4.131
Maybe it could be done now

**Comment by guruas3** [comment]
bump. new release by open shell is available for a while

**Comment by AdmiringWorm** [comment]
I'm afraid that unless someone is willing to open a PR to migrate the current package to `open-shell`, then unfortunately that is unlikely to happen.

I honestly have limited time to use on chocolatey packages nowadays, and this isn't really one of my priorities when working on packages.

This issue is marked as `Up for grabs`, so anyone can open a PR to make the necessary changes.

**Comment by bcurran3** [comment]
There is a RFM for Open-Shell as well:
https://github.com/chocolatey/chocolatey-package-requests/issues/444

**Comment by bcurran3** [comment]
I just published it:
https://chocolatey.org/packages/open-shell/4.4.131

**Comment by majkinetor** [comment]
> EDIT: i.e. classic-shell can be deprecated

Packages do not get deprecated just because the tool is no longer developed. Ideally, we need all of them forever.
