### ISSUE TITLE
(freecad) Add development version

### ISSUE THREAD

**Issue by luzpaz** [chocolatey-community/chocolatey-coreteampackages#1146]
This a continuation of a previous ticket over at https://github.com/chocolatey/chocolatey-package-requests/issues/457#issuecomment-440727605

> There is a stable version package for FreeCAD at [chocolatey.org/packages/freecad](https://chocolatey.org/packages/freecad)
> The request to is to make a package that the windows users can install, test and utilize all the cutting edge development for FEM Workbench, Path/CAM, etc..etc...
> This is also relevant because FreeCAD has such a long release cycle.
> Releases can be viewed at [FreeCAD/FreeCAD/releases](https://github.com/FreeCAD/FreeCAD/releases)
> O.18_pre specifically at [FreeCAD/FreeCAD@`0.18_pre` (release)](https://github.com/FreeCAD/FreeCAD/releases/tag/0.18_pre)

**Comment by RedBaron2** [comment]
@AdmiringWorm 
Just a quick question. Did you have in mind that this could be `--pre`, regular, and ??? packages. The other option I was thinking was to split the package as streamed `x86`, `x64`, and `--pre` builds?

**Comment by AdmiringWorm** [comment]
> Just a quick question. What did you have in mind that this could be --pre, regular, and ??? packages. 

The portable packages (`freecad.portable`) would contain the stable archives and the development editions (dev editions would be installed when using `--pre`, otherwise stable).

> The other option I was thinking was to split the package as streamed x86, x64, and --pre builds?

We do not split up packages into different architectures, and usually not when it comes to `--pre` builds either.

**Comment by RedBaron2** [comment]
@AdmiringWorm 
I guess my use of the word `split` and your definition prompted your reply.
-anyway-
I have a question as to the versioning issue. 
What is the `Standard` for packages that have minor differences like ex: FreeCAD.
_x86: 0.17.13528_
_x64: 0.17.13541_
I only ask because FreeCAD's release page list these as `0.17` releases and not the extra revision numbers.

**Comment by AdmiringWorm** [comment]
> I guess my use of the word split and your definition prompted your reply.

Yeah, pretty much.

> I have a question as to the versioning issue.
> What is the Standard for packages that have minor differences like ex: FreeCAD.
> x86: 0.17.13528
> x64: 0.17.13541
> I only ask because FreeCAD's release page list these as 0.17 releases and not the extra revision numbers.

Well, there isn't really any standard.
But for this package, we've pretty much used all three parts of the version.
What I changed to make it work with minor differences was to use the version of the highest one.
Normally when they release a new version, both the 32bit and 64bit version matches, but if a bug fix is needed for only one of the architectures, they only update the installer that is needed.

**Comment by RedBaron2** [comment]
Progress is being made for the update of this package. Just working on the install scripting now.
Will work on submitting a WIP next week 🤞

**Comment by luzpaz** [comment]
@RedBaron2 please reach out to @sgrogan in the [FreeCAD forums](https://forum.freecadweb.org/viewtopic.php?f=8&t=31893) to coordinate your efforts. He mainly directs the Linux and Windows FreeCAD builds.

**Comment by sgrogan** [comment]
Hey guys!
The reason that the versions don't match is that I have a problem with the x86 build on my system. The update actually had more to do with OSX so I haven't worked too hard to fix it. FreeCAD is getting ready for an 0.18 release so my time has been spent on that.

If you have any thoughts on https://forum.freecadweb.org/viewtopic.php?f=10&t=32738 I'd be interested.

**Comment by RedBaron2** [comment]
@luzpaz 
I just posted on the FreeCAD Forum about finding the "freecad-daily" mentioned by @sgrogan 

I am also posting here since @sgrogan has joined here too.
I can't seem to find any reference to the "freecad-daily" for windows builds.
Thanks to all for any Assistance

**Comment by RedBaron2** [comment]
Quick question do we need to create desktop icons for the dev versions?
Also do we just delete the created directory for the dev versions?

**Comment by RedBaron2** [comment]
@AdmiringWorm @luzpaz @sgrogan 
Just curiosity questions

- Should I enable the package to have `PP` for user directory and/or desktop shortcuts?
- Or do I just dump the Delta versions in the lib FreeCAD directory?

I would like to have this package progressing forward, but without any reply from those that use the Program this is quite a task.

**Comment by luzpaz** [comment]
@RedBaron2 sorry mate. Do you mind continuing the conversation on the forums. We're in the midst of a release so there are a lot of things going on. It would be great if we got this synchronized with all the other release efforts. Thanks!

**Comment by luzpaz** [comment]
Any progress?

**Comment by RedBaron2** [comment]
@luzpaz 
I don't use the program, and don't want to just dump the dev release in ontop of the current stable. 

- I'm just wanting to know where the user wants to drop the dev versions?
- I also want to know if they want a new shortcut on the desktop?

These are questions I've asked here and on the FreeCAD forums with no real answer. 

The update script grabs the stream fine, but the install part is the problem now.

**Comment by luzpaz** [comment]
Can you ask the user if they want a shortcut ?  
Where are other chocolatey dev version packages 'dumping' their installs ?  
Sorry for the lack of response, lets see what I can stir up.

**Comment by AdmiringWorm** [comment]
> Where are other chocolatey dev version packages 'dumping' their installs ?

@luzpaz that usually depends on the software. But most packages don't handle a dev version any different than a stable release (other than releasing it as a pre-release that is).

So it would be more a question of what will be expected by the user, rather than what other dev version packages dump the installation.

So let us rephrase the question a little, when a user is going to launch the program. How is it expected that the user do this? From a desktop icon, start menu icon, commandline, the installation folder?

If it is expected to be 1 or more of the first three options, then it doesn't matter where the installation is located.
If it is the last one, the installation would most likely be installed to a directory in `C:\tools` (can be overridden by the user by an environment variable), the name of the folder that would be inside `C:\tools` would be uncertain at this time though.

**Comment by RedBaron2** [comment]
@AdmiringWorm @luzpaz 
The stable release uses a installer program, and this will follow certain rules. The dev releases come as a standalone version of the application inside a 7zip file. The conundrum comes from a person can have both the dev & stable releases on their system at the same time. I have read on the FreeCAD forums that it is even encouraged by some.

The options are to 
- [ ] Extract the Developmental Releases into the `lib` folder and let the user of Chocolatey fight with how they want to run it. { It will be executable from the command line because it will be on the path. ex: package [`rufus`](https://chocolatey.org/packages/rufus) }
- [ ] Extract the Developmental Releases into the `lib` folder and have a Desktop Shortcut created for the executable file. { This is how most installer programs handle a install. }
- [ ] Extract the Developmental Releases into the `lib` folder and prompt the user for input via command line or powershell. { This is not preferred especially from a Core-Team package. }
- [ ] Extract the Developmental Releases into the `lib` folder by default with a desktop shortcut, but give the user options to change folder location and yes/no shortcut via `PP` options. { This is has been done on other Core-Team packages. } ^ This is also my preference

I'll be putting together a WIP of this package soon.

**Comment by AdmiringWorm** [comment]
The third item won't be accepted on the community repository.
While there are some packages that can only be installed through user input, these need to come in the form of package parameters, and is only accepted if it is truly necessary by the underlying software (which in these case it is not).

Agree with the other points though.

**Comment by luzpaz** [comment]
@RedBaron2 Very nicely summarized. 
Options that I resonate with in the order of preference: 4, 2, 1

**Comment by RedBaron2** [comment]
This is just a update for this issue. The (WIP) PR is working to get the latest versions and install with `pp` to have user choice(s) besides the defaults. I'm working on the uninstaller to remove the shortcat/taskbar options if the users chooses those `pp`. I need to get some details from a higher source. Stay tuned.

**Comment by RedBaron2** [comment]
@luzpaz @AdmiringWorm @sgrogan 
I've decided that the best option for the shortcut/taskbar option is a `pp` option. The snag is that these won't be removed when the `--pre` build is uninstalled. I can put a warning on the package that these items will not be removed, and must be removed manually. If this is a 👍 for everyone. I will then update the PR #1277 and submit it for review.

**Comment by sgrogan** [comment]
@RedBaron2 
Thanks for working on this. I can see that a lack of an installer for the --pre builds is a heartache. I'll keep searching for a good solution to this.

**Comment by RedBaron2** [comment]
@luzpaz @AdmiringWorm @sgrogan 
The current working PR version will install a shortcut to the desktop by default for the `--pre` builds only. It will uninstall the shortcut also 👍 . Should the user decide to change the shortcut location during install. The variables are stored in a json file to be read by the uninstall script. Thanks to @majkinetor for the suggestion. I hope that this will work for everyone.

**Comment by RedBaron2** [comment]
@luzpaz @AdmiringWorm @sgrogan @majkinetor @gep13 
This has been fixed with #1277 ,but everyone has been busy with other responsibilities that the PR has been forgotten. I don't want the bot to mark this issue as stale as it is fixed. Thanks all for the suggestions, and help.

**Comment by luzpaz** [comment]
Awesome!

**Comment by luzpaz** [comment]
@majkinetor was this ever implemented or just closed ?

**Comment by majkinetor** [comment]
https://github.com/chocolatey-community/chocolatey-coreteampackages/pull/1277
https://chocolatey.org/packages/freecad/0.19.0.20052-dev
