### ISSUE TITLE
(notepadplusplus.install) shim misses the mark

### ISSUE THREAD

**Issue by thendarion** [chocolatey-community/chocolatey-coreteampackages#1198]
notepadplusplus.install messes up the install directory, so it creates a shim that points to nowhere.
this doesn't happen on a fresh system but when it has (or maybe previously had?) notepad++ installed.

## Expected Behavior
notepadplusplus.install finds the install location of notepad++.exe and creates the shim accordingly

## Current Behavior
```
Installing 32-bit notepadplusplus.install...
notepadplusplus.install has been installed.
VERBOSE: Trying local and machine (x32 & x64) Uninstall keys
VERBOSE: Retrieving all uninstall registry keys
VERBOSE: Found 0 keys, aborting this method
VERBOSE: Trying Program Files with 2 levels depth: C:\Program Files C:\Program Files\*\* C:\Program Files (x86) C:\Program Files (x86)\*\*
VERBOSE: Trying native commands on PATH
VERBOSE: Trying Registry: \SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths
VERBOSE: No location found
WARNING: Can't find notepadplusplus.install install location
 ShimGen has successfully created a shim for npp.7.6.2.Installer.x64.exe
 The install of notepadplusplus.install was successful.
  Software installed as 'exe', install location is likely default.
```

I found this in my registry
```
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\notepad++.exe]
@="C:\\NPP\\notepad++.exe"
```
so I don't know why `Trying Registry: \SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths` did not pick it up.

However, the order is wrong.

`Trying Program Files with 2 levels depth: C:\Program Files C:\Program Files\*\* C:\Program Files (x86) C:\Program Files (x86)\*\*` picks up any leftover Notepad++ folders from previous installations.

`Trying native commands on PATH` picks up any leftover shims in chocolatey\bin.

## Steps to Reproduce (for bugs)
1. install NPP from a non-chocolatey source to a non-standard folder (like c:\NPP)
2. install NPP through chocolatey

## Context
trying to install NPP where the system has or had NPP already

## Your Environment
Chocolatey v0.10.11
notepadplusplus.install 7.6.2

**Comment by AdmiringWorm** [comment]
Thank you for opening this issue, as I mentioned on the disqus forum I plan to look into this. (Hopefully sometime this week).

**Comment by AdmiringWorm** [comment]
Seems like the changes needed is necessary to be done in the `chocolatey-core.extension` dependency, as such we'll need to fix it there first before we can update the package.

While changing the order when we're checking the `App Path` registy settings, it's unlikely we'll change that right now. However, because of the name `Notepad++` a fix is needed when checking the uninstall part of the registry, which also is something that will fix the issue you're seeing.

**Comment by majkinetor** [comment]
After the WARNING, the script exits, so what creates the shim ?

**Comment by AdmiringWorm** [comment]
@majkinetor seems like choco itself is creating the shim for the installer.
The script returns before the installer gets removed.

I missed that initially as my focus was really on why the package couldn't find the installation path.

**Comment by majkinetor** [comment]
Yes looks like a bug in choco.

**Comment by AdmiringWorm** [comment]
No, not in choco. The bug is actually in the package.

We are trying to get the install location on [line 17](https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/72ae1d58e16f2af5da0dbe0d4c3234061ae98353/automatic/notepadplusplus.install/tools/chocolateyInstall.ps1#L17),
if there is no install location, the package returns on [line 18](https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/72ae1d58e16f2af5da0dbe0d4c3234061ae98353/automatic/notepadplusplus.install/tools/chocolateyInstall.ps1#L18).
However the code for removing the installers is on [line 23](https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/72ae1d58e16f2af5da0dbe0d4c3234061ae98353/automatic/notepadplusplus.install/tools/chocolateyInstall.ps1#L23) which the script never gets to if the install location isn't found.

There is also the problem with the installation directory not being found though.

**Comment by majkinetor** [comment]
You are right - the line that deletes the file is usually not at the end of the script but immediately after `Install-Chocolatey***`.

**Comment by majkinetor** [comment]
>  install NPP from a non-chocolatey source to a non-standard folder (like c:\NPP)
>  install NPP through chocolatey

Reviewing this, I don't think this issue deserves more time. I encountered this behavior number of times with other packages too. Pre-existing installations on custom locations can sometimes mess up things. This concrete problem is related to symbols in executable name (#870) and thus is IMO something we can live with, especially as it can't be resolved quickly and benefit is very small.

I think we should close this.

**Comment by thendarion** [comment]
yes, it is a very niche issue :D

is it worth providing a workaround for in the documentation?

**Comment by majkinetor** [comment]
Yeah, I will close this and add note in the chocolatey core extension.

Thanks.
