### ISSUE TITLE
(brave) wont update with exit code -2147219198

### ISSUE THREAD

**Issue by JipSterk** [chocolatey-community/chocolatey-coreteampackages#1258]
## Expected Behavior
Brave should update to the latest version

## Current Behavior
when you enter `choco upgrade brave` in a powershell terminal with admin rights its says its downloading the latest version. then i opens a new brave window but choco spits out an error like this
```ps
ERROR: Running ["C:\ProgramData\chocolatey\lib\brave\tools\BraveBrowserStandalon
eSilentSetup.exe" ] was not successful. Exit code was '-2147219198'. See log fo
r possible error messages.
The install of brave was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\brave\tools\chocolateyInstall
.ps1'.
```

## Your Environment
* Package Version used: 
* Operating System and version: Version 10.0.17763 Build 17763
* Chocolatey version: 0.10.13

**Comment by majkinetor** [comment]
Do you still have a problem updating it ?

**Comment by JipSterk** [comment]
to be honest haven't really keep an eye out for this issue. Maybe i reinstalled it when i upgrade it doesn't spit out an error.

**Comment by eyadsibai** [comment]
I am getting similar error with brave too

**Comment by majkinetor** [comment]
Similar?

**Comment by eyadsibai** [comment]
same exit code when trying to upgrade or reinstall

**Comment by timkatje** [comment]
This behavior has just started on my system as well.  Brave is automatically updating itself to keep up with the latest, and since I have Chocolatey Pro, it should be syncing and detecting the updates, but I've found that's usually not the case with auto-updating browsers (Chrome seems to have the same issue on my systems).

Anyway, Brave was installed by chocolatey at version 1.0.1, and Chocolatey wants to update it to version 1.2.42.  But Brave has updated itself to "Version 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit)."

So perhaps it has something to do with the Brave installer already detecting a newer version is installed and is thus preventing a downgrade.  I'll retry this again if/when 1.2.43 package is approved on Chocolatey (or any newer one).  The catch is, the delay between Brave release and Chocolatey may be too great to keep up with and I'll end up just pinning it like my other auto-updating apps.
