### ISSUE TITLE
(putty) install does not create Start Menu entries

### ISSUE THREAD

**Issue by wesinator** [chocolatey-community/chocolatey-coreteampackages#1274]
## Expected Behavior

Create start menu folder for PuTTY programs on install

## Current Behavior

No start menu folder is created. Programs must be manually executed from command-line.

## Steps to Reproduce (for bugs)

1. `choco install putty`
2. Open start menu folder

## Your Environment

* Package Version used: 0.71
* Operating System and version: Windows 8.1 Pro x64
* Chocolatey version: 0.10.13
* Install/uninstall gist:

**Comment by AdmiringWorm** [comment]
The `putty` package depends on `putty.portable` (which handles the installation).
That package do not install icons to the start menu by design, as this would require administrative privileges (due to packages being installed systemwide) and portable packages should **not** require administrative privileges to be installed.

There is a solution for you though, install the `putty.install` package instead, this package uses the putty installer which I believe also installs icons to the start menu.

**Comment by cinderblock** [comment]
For those that come across this issue in the future, it seems it has been decided that PuTTY is a special package that doesn't follow the official conventions, even though Chocolatey devs thought this was already changed. https://github.com/ferventcoder/chocolatey-packages/issues/100#issuecomment-163054316

#1177 - People think it's a breaking change. It's not
#1293 - They refuse to put a warning up
