### ISSUE TITLE
Git Installer always disables symlinks no matter what

### ISSUE THREAD

**Issue by JackZylkin** [chocolatey-community/chocolatey-coreteampackages#1281]
NOTE: This is a clone of issue #631 , which was closed based on a false assumption about the git installer.  The git installer cannot detect whether symlinks should be enabled or disabled if it is run in Admin mode. As far as I know Chocolatey is always run in Admin mode. Therefore the git installer must be instructed explicitly what to do about symlinks -- otherwise they revert to being disabled.  

You can try this yourself by running
ntrights.exe -u %username% +r SeCreateSymbolicLinkPrivilege
Then opening up a new shell and installing "choco install git" 
Now, init or clone a new repo, and observe that the .git/config file has "Symlinks=false"
 -- Even though your account has the right privileges, git has disabled symlinks.

FROM original issue #631 :
> Git Installer added the option to enable symbolic links. Add an install parameter to configure the setting.
> To stay consistent with existing parameters, the registry item is: Inno Setup CodeFile: Enable Symlinks. The values are Disabled or Enabled.
> The option should be set to enabled by default on upcoming Windows 10 Creators Update if Developer Mode is turned on, otherwise default to disabled.
> It was disabled on Windows because creating Symbolic Links required Elevated Admin rights making it less user friendly. Creators Update changes this in Developer Mode to allow any user on the machine to set Symbolic Links. See the Windows Blog for more details on the change in Windows.
> Since Symbolic Links is the intended behavior by Git and a top issue, it makes sense to enable this by default with the new support for it. On older versions of Windows, it should remain disabled but optional so that developers that turn off UAC or don't mind the hassle can have it turned on.

**Comment by majkinetor** [comment]
>  As far as I know Chocolatey is always run in Admin mode.

That is not correct: 
- https://chocolatey.org/install#non-administrative-install

Now, this can be done if user has administrative rights, but is running under non-elevated context. One mechanism is installation via scheduled task which is easy to 'fix' (VirtualBox package uses that mechanism). Thinking more about this, the place of the function [Start-ProcessNonElevated](https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/master/automatic/virtualbox/tools/helpers.ps1#L15) might be in the core extension since it is generally useful in this kind of context.

If administrator is entirely different user, I am not sure how it can be done since there must be some way for that user to get the credentials of the invoking user. I guess this not how many people use choco tho.

This can also be done upstream in the git.install installer itself (this might actually be treated primarily as upstream problem).

**Comment by JackZylkin** [comment]
I just did some experimenting and found that, after restarting my computer, git has decided to start setting symlinks=true on all my newly initialized repos.  I don't really know which troubleshooting step fixed the problem exactly, but choco might work correctly in this regard after all.  Thanks for your help.
