### ISSUE TITLE
(paint.net) Should depend on 4.7.2

### ISSUE THREAD

**Issue by gep13** [chocolatey-community/chocolatey-coreteampackages#1299]
## Expected Behavior

Paint.net installs only the required software in order for it to work

## Current Behavior

Installing Paint.Net installs both 4.7.1 and 4.7.2, due to dependencies changes on upstream packages, i.e. dotnet4.7.1.  Paint.net actually requires 4.7.2, so the dependency on 4.7.1 is not correct.

## Possible Solution
Change dependency on be on 4.7.2, rather than 4.7.1.

## Steps to Reproduce (for bugs)
`choco install paint.net`

## Context

Conversation on Twitter regarding this package:

https://twitter.com/mikaelronnback/status/1145358830647353346

## Your Environment

Verified on local Chocolatey Testing Environment

* Package Version used: 4.1.6
* Operating System and version: Windows Server 2012
* Chocolatey version: 0.10.15

**Comment by pascalberger** [comment]
> Installing Paint.Net installs both 4.7.1 and 4.7.2, due to dependencies changes on upstream packages, i.e. dotnet4.7.1. Paint.net actually requires 4.7.2, so the dependency on 4.7.1 is not correct.

It's actually not possible to have both version installed, since the later will overwrite the previous. I also don't see why it should install both currently. Dependency goes to [Microsoft .NET Framework 4.7.1](https://chocolatey.org/packages/dotnet4.7.1), which in its latest version has a dependency to [Microsoft .NET Framework](https://chocolatey.org/packages/dotnetfx), which will install the latest available version at the time of install, assuming no .NET Framework is installed. If it is already installed through Chocolatay in a version satisfying the dependency it should do nothing.

**Comment by gep13** [comment]
If you look at the dependency chain, and the way Jakub has built the packages, 4.7.1 depends on latest version of dotnetfx which is currently 4.7.2, which means that both packages are installed, which isn’t correct, even if one overrides the other later in installation.

Paint.net current version requires 4.7.2, and as such I think the dependency should be updated to reflect this.

**Comment by gep13** [comment]
The test I did was on a fresh test environment, and both 4.7.1 and 4.7.2 packages were attempted to be installed.

**Comment by pascalberger** [comment]
There's the difference between Chocolatey package and software being installed. I agree that this will install the `dotnet4.7.1` and `dotnetfx` package (which is currently 4.7.2). But actually installed would only be 4.7.2.

To depend on `dotnet4.7.2` is definitely better. But note that soon this will mean that actually .NET 4.8 will be installed on a clean environment.

**Comment by gep13** [comment]
Understood 👍
