### ISSUE TITLE
(umbrello.install) Latest version exceeds 200 MB

### ISSUE THREAD

**Issue by chtof** [chocolatey-community/chocolatey-coreteampackages#1312]
## Expected Behavior
Be able to submit last version of umbrello.install package.

## Current Behavior
```
-a----       02/08/2019     05:17      198610545 umbrello.install.2.28.3.nupkg

_Containing;_
-a----       02/08/2019     05:16       99762773 umbrello-mingw32-2.28.3-22.1-setup.exe
-a----       02/08/2019     05:17      100542126 umbrello-mingw64-2.28.3-95.1-setup.exe

cpush .\umbrello.install.2.28.3.nupkg
Chocolatey v0.10.15
Attempting to push umbrello.install.2.28.3.nupkg to https://push.chocolatey.org/
An error has occurred. It's possible the package version already exists on the repository.

```
## Possible Solutions
1/ Integrate this package in Chocolatey-coreteam repository who allows packages excedding 200 MB
2/ Change the package to be no longer embedded.

## Previous version with a size of about 154 MB
`a----       11/05/2019     14:26      154240923 umbrello.install.2.27.3.20190511.nupkg`

**Comment by AdmiringWorm** [comment]
> Integrate this package in Chocolatey-coreteam repository who allows packages excedding 200 MB

This is not true, the same restrictions are placed on the core team packages repository as with any other package repository.
The reason why there may be some packages that are above 200MB is because there was a short time this was possible. (this was lowered due to external providers I believe. Can't remember which one right now though).

You're free to open a pull request to migrate the package to this repository, but do note that we have stricter requirements/guidelines than those used in the community repository. So be sure to review the       [Contribution guidelines](https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md) before you do.

Do also note that this repository is not meant as a dumping ground, so as such it is expected that the original maintainer (probably you in this case) is responsible to fix any issues regarding the package (be it problems with the package itself, updater not working, considering new features wanted by the community, etc.). This doesn't mean we won't step in at times though, of course.

**Comment by majkinetor** [comment]
I will close this since it is not relevant for this repository and migration is based on wrong idea. 

For this package I suggest the following solution that we adopted once in the past: provide embedded binary for x64 bit version and keep downloading x32 bit version - since most of the systems today are x64 and x32 bit will eventually be deprecated, this is a good trade for this problem.

If you want to migrate the package here, just do PR and follow the guidelines.
