### ISSUE TITLE
(ruby) Remove previous version in update process

### ISSUE THREAD

**Issue by Kristinita** [chocolatey-community/chocolatey-coreteampackages#1317]
### 1. Summary

It would be nice, if previous Ruby versions will be removed in updating process.

### 2. Argumentation

I run [**SpaceSniffer**](https://chocolatey.org/packages/spacesniffer) → I saw, that previous Ruby versions — that I install solely via Chocolatey — not deleted:

![SpaceSniffer Ruby](https://i.imgur.com/5NG0NML.png)

I don't need Ruby23, 24 and 25. This is extra folders, which occupy gigabytes of disk space.

### 3. Steps to reproduce

```text
cup ruby -y
```

### 4. Current behavior

Previous Ruby versions not deleted.

### 5. Example of expected behavior

1. Delete old Ruby version. «Update» in my understanding is not «add new and preserve previous version».
1. If user want to have multiple specific Ruby versions, better to have **#1298** behavior.

Thanks.

**Comment by AdmiringWorm** [comment]
> Delete old Ruby version. «Update» in my understanding is not «add new and preserve previous version».

When they are meant to be installed side-by-side, then this is the side affect of that, and since we can't detect if the argument `--sidebyside` we can't exactly blindly remove the previous version either.

Sure, we could add a `chocolateyBeforeModify.ps1` file that removes the previous version (as that file is run from the package version before updating), but that isn't really the use case of that file.

> If user want to have multiple specific Ruby versions, better to have #1298 behavior.

This is something I strongly disagree with, if you want a polluted repository with duplicated packages, then this is exactly what you need to make that happen.
Using different packages specific to each major/minor version should be used very sparingly, and IMO should be avoided in most cases.

**Comment by majkinetor** [comment]
I think our position is clear here.
