### ISSUE TITLE
(vscode) ContextMenu not working after upgrade

### ISSUE THREAD

**Issue by Duracell1989** [chocolatey-community/chocolatey-coreteampackages#1366]
I've installed VSCode via Chocolatey and this morning I've upgraded VSCode to 1.39.2 via `choco upgrade vscode`. After the installation, the ContextMenu in the Windows File Explorer doesn't work. The ContextMenu is available, but when I click _Open with Code_. I get an error message **Application not found**.
## Expected Behavior
VSCode starts.

## Current Behavior
Explorer.exe reports **Application not found**

## Steps to Reproduce (for bugs)
1. Install (an older version) of VSCode
2. Upgrade to a newer version
3. Right-click in the File Explorer and click Open with Code_

## Your Environment
* Package Version used: 1.39.2
* Operating System and version: Windows 10 Version 1903 (OS Build 18362.418)
* Chocolatey version: v0.10.15

Update:
Uninstalling and (re)installing fixes the issues.
Does upgrading break the ContextMenu entry?

**Comment by majkinetor** [comment]
Cant confirm, I just upgraded on my own machine and it works:

```
You have vscode v1.37.1 installed. Version 1.39.2 is available based on your source(s).
```

Tried on chocolatey test environment with older version 1.35.1, after update to 1.39.2 everything context menu still works.

I will close this because even if its true, there is nothing we do in installer to influence this, so if it happens, its definitelly upstream problem.

**Comment by majkinetor** [comment]
Its local problem, check if vscode is properly installed (can you find code.exe?)
