### ISSUE TITLE
Packages failing to install/upgrade due to chocolatey-core.psm1

### ISSUE THREAD

**Issue by HunterZ** [chocolatey-community/chocolatey-coreteampackages#1373]
(???) Upgrade/install of some packages is failing with the following error message:
```
You must provide a value expression on the right-hand side of the '-' operator.
The specified module 'C:\ProgramData\chocolatey\extensions\chocolatey-core\chocolatey-core.psm1' was not loaded because no valid module file was found in any module directory.
```

## Expected Behavior

Packages install/upgrade without error.

## Current Behavior

I get an error message:
```
You must provide a value expression on the right-hand side of the '-' operator.
The specified module 'C:\ProgramData\chocolatey\extensions\chocolatey-core\chocolatey-core.psm1' was not loaded because no valid module file was found in any module directory.
```

## Possible Solution

I tried forcing a reinstall of chocolatey-core.extension, but it did NOT help.

## Steps to Reproduce (for bugs)

1. cinst -y --force notepadplusplus

## Context

Trying to upgrade my existing package installs.

## Your Environment

* Package Version used: various
* Operating System and version: Windows 10 1903
* Chocolatey version: Chocolatey v0.10.15
* Install/uninstall gist: https://gist.github.com/HunterZ/65c5a5a6417efe9ad0182c96f0c19085

**Comment by HunterZ** [comment]
The following files are in C:\ProgramData\chocolatey\extensions\chocolatey-core:
```
chocolatey-core.psm1
Get-AppInstallLocation.ps1
Get-AvailableDriveLetter.ps1
Get-EffectiveProxy.ps1
Get-PackageCacheLocation.ps1
Get-PackageParameters.ps1
Get-UninstallRegistryKey.ps1
Get-WebContent.ps1
Register-Application.ps1
Remove-Process.ps1
```

**Comment by HunterZ** [comment]
Used Chocolatey GUI to update the affected packages, and it worked fine. I wonder if CMD.EXE is invoking the wrong version of PowerShell or something?

**Comment by majkinetor** [comment]
I will close this as it is 99% some effect specific to your system. If it happens again to you let us  know here.

**Comment by Moth-Tolias** [comment]
i'm getting this too, happening for np++ and qbittorrent.
what gets me is that the specified file [chocolatey-core.psm1] is right there, but i still get the error...

**Comment by f** [comment]
I have nothing to do with this 😅

**Comment by majkinetor** [comment]
Nice catch @AdmiringWorm

**Comment by john3voltas** [comment]
Ok, I had this same issue and apparently I was able to workaround by simply:

> 'choco install powershell -y'

What happens is that this way I upgraded the powershell and now even when I am invoquing choco from a CMD shell everything works just fine.

Please be advised that if you upgrade powershell through choco you may find an issue where Windows upgrades the powershell app and then it needs to restart but Windows apparently doesn't inform choco of that.
So I stood there waiting for choco to finish upgrading PS for more than 2 hours while the Windows Update window kept nagging me that it needed to restart Windows. I thought it was nagging me due to other updates that had nothing to do with choco, so I waited while I was working on other stuff.
But since it was taking so much time I then decided to stop choco, rebooted "et voilá", PS had actually finished upgrading and now both CMD and PS work fine for using choco.
Thanks.
Cheers

**Comment by AdmiringWorm** [comment]
A new version of the [`chocolatey-core.extension`](https://chocolatey.org/packages/chocolatey-core.extension/1.3.5) have been pushed to chocolatey.org. Once that version have completed the automated checks, do the following:

1. First update the extension (`choco upgrade chocolatey-core.extension`)
2. Install the package you want.

Alternatively, you do as @john3voltas and upgrade powershell instead to fix the problem.

**Comment by john3voltas** [comment]
Great work.
Thanks, @AdmiringWorm
