### ISSUE TITLE
(mpc-hc-clsid2) Package failed automated validation

### ISSUE THREAD

**Issue by jack1142** [chocolatey-community/chocolatey-coreteampackages#1404]
(I'm not going to follow issue template, since it doesn't seem to work well for this kind of issue)
Hi, here's maintainer of `mpc-hc-clsid2` that is placed in this repository. I got an email about the package failing automated validation due to invalid url in `DocsUrl` element in nuspec. I noticed 2 things though, firstly I don't see 1.9.0 update in this repository, last update to the package was in October and secondly the DocsUrl for this package works so I'm guessing this was some server failure around the time it was validated.
So, I would like to ask if I can do anything to help with this.

**Comment by AdmiringWorm** [comment]
@jack1142 The failure is because of cloudflares DDos protection. The url can only be accessed through a web browser (or at least something that runs javascript, and don't trigger a failure in their ddos check).

Not sure what appropriate changes we should make regarding this though, most likely we'll have to remove the Documentation url. At least until the validator can handle those kind of urls, or won't require a change in these cases.

Whatever change will be done may depend on what changes the following issues will implement: https://github.com/chocolatey/package-validator/issues/200 , https://github.com/chocolatey/package-validator/issues/202

**Comment by AdmiringWorm** [comment]
>  I noticed 2 things though, firstly I don't see 1.9.0 update in this repository, last update to the package was in October and secondly the DocsUrl for this package works so I'm guessing this was some server failure around the time it was validated.

Most likely, we got an origin time-out during the push.
It usually goes through in these cases, but is detected as an error by AU and won't update the repository. (Not really that important, and the detection is correct)

**Comment by gep13** [comment]
@jack1142 this package version has now been approved.  Thanks for raising this issue with the package-validator.
