### ISSUE TITLE
(firefox) extend package to integrate the installer command-line options

### ISSUE THREAD

**Issue by FreeMinded** [chocolatey-community/chocolatey-coreteampackages#1409]
The Firefox Installer support a range of command-line options [1]. This package currently has no support for them. The command-line options are useful i.e for defining if a desktop shortcut should be created, if the configurations set through distribution/policies.json should be kept and a few more.

## Expected Behavior
Command-line Options can be passed to the installer through the --params mechanism.

## Current Behavior
As a workaround command line options can be passed using --install-arguments or -ia. But this does not allow to check for correct input or to set defaults in the package which differ from the installer defaults.

## Possible Solution
Implement package parameters in the package. An example implementation could be seen in the Wazuh agent package [2]. 

1: https://firefox-source-docs.mozilla.org/browser/installer/windows/installer/FullConfig.html
2: https://github.com/itigoag/chocolatey.wazuh-agent/blob/master/package/tools/chocolateyinstall.ps1

**Comment by FreeMinded** [comment]
We actually offer to create a pull request for this if there is a reasonable change to get it approved.

**Comment by AdmiringWorm** [comment]
Feel free to open a PR to add this functionality.

As long as all the changes follow our [Contrubution Guidelienes](https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md) there are a high likelihood that it will be accepted.

Be aware that it can take time sometimes before a PR is pulled in, mainly because the main maintainers here is doing all this on their spare time, and may have other priorities than reviewing pull requests.

**Comment by FreeMinded** [comment]
I just updated the PR to reflect the current FF version. Any chance we can get this reviewed before the next release?
