### ISSUE TITLE
(libreoffice-fresh) new version available upstream

### ISSUE THREAD

**Issue by opusforlife2** [chocolatey-community/chocolatey-coreteampackages#1442]
Version 6.4.1 is available since 27 Feb, 2020.

**Comment by majkinetor** [comment]
It looks like stream updater is not working...

https://gist.github.com/choco-bot/a14b1e5bfaf70839b338eb1ab7f8226f#libreoffice-streams

/cc @wget @AdmiringWorm

**Comment by RedBaron2** [comment]
This could be due to the website update check.php being changed to silverstripe by TDF.
Also in looking around [TDF forums](https://ask.libreoffice.org/en/question/163761/check-for-update-tells-me-im-up-to-date-when-im-not/) I found a interesting quote

> I have found that on Windows neither the manual or automatic update check **_works reliably_**.

I have a suggestion of using a fallback method of checking for updates like parsing the website as was done before.

**Comment by AdmiringWorm** [comment]
Version 6.4.2 has been available since March 26th.

@majkinetor The stream updater is working. It just won't show up correctly when there aren't any updates (no idea why).

Please also see the featured comment on why there aren't immediate updates for the libreoffice-fresh package: http://disq.us/p/252gp74

Anyways, I will be closing this issue now.

**Comment by majkinetor** [comment]
> The stream updater is working. It just won't show up correctly when there aren't any updates (no idea why).

That is the only one with this problem AFAIK.

**Comment by AdmiringWorm** [comment]
@majkinetor yeah it is. I believe @wget just returns empty streams when the locations that is used returns an error, or not the information that is expected.

I can't say for sure without digging into it though. Busy with going through some packages that have been failing during the couple of months I've been away from chocolatey package maintenance, and that it isn't something I will be prioritizing going through digging into either.

**Comment by wget** [comment]
> This could be due to the website update check.php being changed to silverstripe by TDF.
Also in looking around TDF forums I found a interesting quote

It is not applicable any more.

The update checked has been completely rewritten in lua and even if we call a check.php page for legacy reasons, this is the lua code that is responding =)

> @majkinetor yeah it is. I believe @wget just returns empty streams when the locations that is used returns an error, or not the information that is expected.

I'll investigate this. But for the record, I'm "hacking" the way streams are working so it may be the reason. The hack was to avoid gaps in the versions: when a stream is becoming the oldstable, e.g. 6.3 versions between 6.3.0 and 6.3.4 (for example) weren't pushed. The script is huge and is rebuilding a whole map of all the version in memory before taking decision :)
