### ISSUE TITLE
(tor-browser) outdated and installer source is no longer available

### ISSUE THREAD

**Issue by pseigo** [chocolatey-community/chocolatey-coreteampackages#1449]
The package is set to use tor-browser version 9.0.5 which is no longer available on the website (at https://dist.torproject.org/torbrowser/9.0.5/<build>). The latest version (as of this issue) is 9.0.7. Currently, they're hosting 9.0.6 and 9.0.7, but with such a short hosting cycle this issue will probably happen again with future releases. Perhaps there's some way to automate this for minor versions?

```
Downloading tor-browser 64 bit from 'https://www.torproject.org/dist/torbrowser/9.0.5/torbrowser-install-win64-9.0.5_en-US.exe'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://www.torproject.org/dist/torbrowser/9.0.5/torbrowser-install-win64-9.0.5_en-US.exe'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
```

## Environment

* Package Version used: 9.0.5
* Operating System and version: Windows 10 Education 1809
* Chocolatey version: v0.10.15
* Install/uninstall gist: https://gist.github.com/pseigo/08a47a4283fbd8c29f6f3d59533d668a

**Comment by AdmiringWorm** [comment]
Version `9.0.7` (and `9.0.6`) have been pushed to chocolatey.org, but unfortunately it is currently failing the automated verification step.

Unfortunately I do not have the possibility at the moment to look into why this happens, but will mark this as an up for grabs in case anyone is interested in looking into it:

Logs: https://gist.github.com/choco-bot/7d1b946792b2be678b54fbb038da409b

**Comment by RedBaron2** [comment]
@AdmiringWorm 
The verification failed because it was unable to download the file.
`2020-03-24 21:04:56,874 2092 [ERROR] - ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://www.torproject.org/dist/torbrowser/9.0.7/torbrowser-install-win64-9.0.7_en-US.exe'. Exception calling "GetResponse" with "0" argument(s): "The request was aborted: Could not create SSL/TLS secure channel."
 at Get-WebFile, C:\ProgramData\chocolatey\helpers\functions\Get-WebFile.ps1: line 331`
The URL is fine and the package installs correctly even uninstalls correctly. The verifier just needs to be re-ran again. No need to force a new package. The **Verifier Failed** having a _internet_ connection for some _unknown_ reason

**Comment by AdmiringWorm** [comment]
@RedBaron2 hmm, certainly looks that way. I didn't look at the logs, to be honest. I have set the latest version of `tor-browser` to run again, so hopefully everything works as it should now then.
If not, this will need to be dug into further to find the cause.

**Comment by AdmiringWorm** [comment]
@RedBaron2 you were right, there was an intermittent issue with the Verifier.

The latest version of the tor-browser is now available for consumption.

I will trigger a re-run of the 9.0.6 version as well so we have that also.

**Comment by AdmiringWorm** [comment]
Seems 9.0.6 still fails the verifier, as such, I will be rejecting that version instead of wasting any time on trying to make it work, considering that 9.0.7 works.
