### ISSUE TITLE
(autohotkey) ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 

### ISSUE THREAD

**Issue by basictheprogram** [chocolatey-community/chocolatey-coreteampackages#1478]
## Expected Behavior
`choco install autohotkey` should install the autohotkey package

## Current Behavior
The package throws an error.
```
autohotkey.portable v1.1.14.01 [Approved]
autohotkey.portable package files upgrade completed. Performing other installation steps.
Attempt to get headers for http://l.autohotkey.net/v/AutoHotkey111401_x64.zip failed.
  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'http://l.autohotkey.net/v/AutoHotkey111401_x64.zip'. Exception calling "GetResponse" with "0" argument(s): "The underlying connection was closed: The connection was closed unexpectedly."
Downloading autohotkey.portable 64 bit
  from 'http://l.autohotkey.net/v/AutoHotkey111401_x64.zip'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'http://l.autohotkey.net/v/AutoHotkey111401_x64.zip'. Exception calling "GetResponse" with "0" argument(s): "The underlying connection was closed: The connection was closed unexpectedly."
The upgrade of autohotkey.portable was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\autohotkey.portable\tools\chocolateyInstall.ps1'.
 See log for details.
```

## Steps to Reproduce (for bugs)

1. choco install autohotkey
## Your Environment

* Package Version used: autohotkey.portable v1.1.14.01 
* Operating System and version: Windows10 Professional
* Chocolatey version: chocolatey 0.10.15
* Install/uninstall gist:

**Comment by basictheprogram** [comment]
The GitHub releases for 1.1.14 is only available in source form
```
https://github.com/Lexikos/AutoHotkey_L/releases/tag/v1.1.14.04
```

You could upgrade the latest 1.1 series and fix the url with this:
```
https://github.com/Lexikos/AutoHotkey_L/releases/download/v1.1.32.00/AutoHotkey_1.1.32.00_setup.exe
```

**Comment by basictheprogram** [comment]
Database issue on the community feed from chocolatey.org?

Why is as `choco install autohotkey` attempting to grab release 1.1.14.01?

Looking at the the chocolatey.org community feed I see 1.1.32.00 is available there and looking at the .nuspec files I see they are 1.1.32.00

Very confused right now

**Comment by AdmiringWorm** [comment]
Such an old version is not supported on that package, and there isn't anything we can do about chocolatey picking an older version instead of the correct version.

Such a problem would need to be reported over at https://github.com/chocolatey/choco as it isn't a package problem.

Also, make sure that you don't have additional installation sources that contain the `autohotkey` package (I did notice that you showed logs from `autohotkey.portable` and not `autohotkey`, which doesn't make sense unless you have a custom `autohotkey` package somewhere).

As this isn't considered a package problem (at least not for a supported version), I will be closing this issue.
