### ISSUE TITLE
(python) Pip cannot build C modules

### ISSUE THREAD

**Issue by metamarcdw** [chocolatey-community/chocolatey-coreteampackages#1518]
## Expected Behavior
Pip builds and installs C-based Python modules without issue

## Current Behavior
Pip fails to build certain modules with this error: "error: Microsoft Visual C++ 14.0 is required."

## Steps to Reproduce (for bugs)
1. Install Python using `choco install python`
2. Create a virtual environment using `python -m venv`
3. Attempt to install a module which uses C bindings, for example using `pip install misaka`

## Context
I am trying to work on a Flask app which uses Flask-Misaka

## Your Environment
* Package Version used: Python 3.8.5
* Operating System and version: Windows 10
* Chocolatey version: 0.10.15
* Install/uninstall gist: ?

**Comment by majkinetor** [comment]
So you want dependency added to  Microsoft Visual C++ 14.0 ? Did you try it manually ?

**Comment by majkinetor** [comment]
I am having this "problem" myself, and I think this should not be part of the package as it significantly increases setup time. 

I will add some info in the Notes section on how to do this.

**Comment by majkinetor** [comment]
I found out that

```
choco install -y python3
pip install --upgrade setuptools
choco install visualstudio2019-workload-vctools
```

builds the stuff I wanted (locust).  This literary installs what is mentioned here:
* [Microsoft Visual C++ 14.2 standalone: Build Tools for Visual Studio 2019 (x86, x64, ARM, ARM64)](https://wiki.python.org/moin/WindowsCompilers#Microsoft_Visual_C.2B-.2B-_14.2_standalone:_Build_Tools_for_Visual_Studio_2019_.28x86.2C_x64.2C_ARM.2C_ARM64.29)

The problem here is that it installs 5+GB of stuff. 

I tested this on pristine Windows Sandbox and it goes without restart and builds C++ stuff (gevents etc.)

I guess we can get lower with [mingw](https://wiki.python.org/moin/WindowsCompilers#GCC_-_MinGW-w64_.28x86.2C_x64.29) system but I didn't try it yet.

I remember @cclauss had valuable input on python before, so maybe he could provide some more info.

**Comment by naveen521kk** [comment]
I am against install Visual Studio by default with Python. It's useless for people who don't use a C module or build one. Usually, maintainers produce [wheels](https://pythonwheels.com/) so that they can be installed without any compiling work. For example, [Numpy](https://pypi.org/project/numpy) and [Scipy](https://pypi.org/project/Scipy). 

You should either ask for the project maintainers to Publish wheels or rather help them in building them. 

> I guess we can get lower with mingw system but I didn't try it yet (also says it works up to python 3.4)
About [`mingw`](https://wiki.python.org/moin/WindowsCompilers#GCC_-_MinGW-w64_.28x86.2C_x64.29) it is unsupported by the Python installed using Chocolatey or rather the default one because an extension should only be built with MSVC. If you want to use `mingw` then you should install `msys2` and install their Python using their package manager.

**Comment by majkinetor** [comment]
I agree.

I will just add above info in readme and call it a day.
