### ISSUE TITLE
(kitty) High Virus Count for klink.exe (0.74.2.7)

### ISSUE THREAD

**Issue by pauby** [chocolatey-community/chocolatey-coreteampackages#1563]
We've had another report about the [kitty package](https://chocolatey.org/packages/kitty/0.74.2.7#virus) high virus count for klink.exe. It's currently standing at 7 detections which is above the threshold we'd consider a false positive and as such we'd need to reject it without a good explanation backed up from the vendor / author.

I've submitted it back to the Package Scanner just now to rerun the scan. Does anybody have any thoughts?

Previous issue was raised at #1427

**Comment by jaynemo** [comment]
Apparently this is due to poor-quality virus scanners flagging it over the use of UPX to reduce the size of the executable. I see that the latest version on chocolatey, 0.74.2.8 seems to trigger less issues on VirusTotal.

The author now builds an uncompressed version that avoids those issues which is apparently used by scoop- maybe it would be best to switch to that for the packages.

**Comment by pauby** [comment]
I'd disagree this is poor quality virus scanners:

![image](https://user-images.githubusercontent.com/12760779/98447321-cce00880-211b-11eb-8e2d-43e9c5c11feb.png)

But I take your point.

The latest doesn't have AV results as yet but the 0.74.2.8 is flagged by 6 AV scanners. This is still too high without an explanation by the vendor / author. Do we have something we can point to in the nuspec description?

If the uncompressed version doesn't get picked up by the scanners in the same way I'd think this would be a better way to go.

**Comment by jaynemo** [comment]
It looks to be primarily the result of some scanners, including, unfortunately, Defender, picking up on the UPX-compressed klink.exe which is included in the executables to be installed. Decompressing klink.exe takes that down to 2 results on VirusTotal. Unless I'm missing something, that's strongly suggestive of spurious results.

I've asked about whether it would be possible to have a non-UPX'd exe for the various 'extra' exes that are part of the KiTTY package. I suppose an alternative would be to exclude klink.exe in the nuspec package, though that might be problematic for anyone actually using it, or to un-UPX the executables in the AU package build so that the ones in the .nupkg aren't flagged, though I imagine that could still cause problems for people running their own local AU package builds.

**Comment by majkinetor** [comment]
Maybe we should just add note and call it a day. We know this is not a virus and know the reasons for it being reported.

**Comment by pauby** [comment]
I think we need to get this issue resolved permanently rather than closing it as we'll have the same issue with the next version and the next.

> We know this is not a virus and know the reasons for it being reported.

_We_ may know the reasons. _I_ don't know it's not a virus. But more importantly users of the package and the site don't know the reasons OR whether it's a virus. They look at the AV scores. They see Defender quarantining it and that is enough for them to label the package and software as malware. That isn't in anybody's best interests. So we should fix the problem as best we can so that Chocolatey and kitty are not getting a bad reputation.

If the problem is the EXE compression then the author needs to remove it. The author needs to also explain what they believe the reasons are for having the high number of AV detections on their software. If they do that / have already done that, then a note explaining that, and pointing to the authors official explanation should be added to the description of the package. The author is free not to do any of that but then we need to take a decision in that do we (as in Chocolatey, maintainers and moderators) waste time having these discussions, moderating packages, answering questions from users etc. or do we just remove the package.

I've rejected v0.74.2.7. We also have v0.74.2.8 and v0.74.3.1 with 6 detections each for klink.exe (and a couple of others). This also needs to be addressed.

**Comment by majkinetor** [comment]
So `genpass`.exe and `klink` are problematic and those DO NOT have uncompressed version.

Since there is really nothing we could do except perhaps uncompress those 2 tools ourselves which seems intrusive to me (we are changing upstream binaries) I am still for the note.

> I don't know it's not a virus.

You can say that for any tool in universe even if we don't tackle your particular personality traits.

I don't see that kitty has a problem with VT, they even link it in download section. Foshub also list it with 0 viruses: https://www.fosshub.com/KiTTY.html 

We are all here hostages of AV companies. We need to defend and inform, not blindly follow into the big hole.  

Hence, I am for the note, we can make it a **REALLY BIG ONE IF YOU WANT.** I will  personally write it which by itself guaranties success.

**Comment by pauby** [comment]
> So genpass and klink are problematic and those DO NOT have uncompressed version.

Then we're back to square one for those at least.

> I don't see that kitty has a problem with VT, they even link it in download section. Foshub also list it with 0 viruses: https://www.fosshub.com/KiTTY.html

The Virus Total detections are on the package page.

**Comment by cyd01** [comment]
Only KiTTY is provided in three versions in [Fosshub page](https://www.fosshub.com/KiTTY.html):
- compressed version pre-configured for registry mode
- compressed version pre-configured for portable mode
- uncompressed version pre-configured for registry mode

To be clear, there is no registry nor portable version. There is only one KiTTY that can be run in two different modes.  
So that uncompressed version can be used in portable mode too. The configuration is describe in this [page](https://www.9bis.net/kitty/#!pages/Portability.md).

No other binaries (including `klink.exe`, `genpass.exe` ...) are compressed.  
Please note that `klink.exe` is 95% `plink.exe` source code. And `plink.exe` has also some false positives: see [Virus Total report](https://www.virustotal.com/gui/file/01678a1d46c240b2e2ea071a5d0d84573632aa835d3240e87c3b99b20537e049/detection) of the version 0.74 of `plink.exe` 64bits.

**Comment by majkinetor** [comment]
Thank you. I think we ca now safely close this. I will add note on package.

**Comment by majkinetor** [comment]
Also, plink doesn't have it in [latest version](https://www.virustotal.com/gui/file/01678a1d46c240b2e2ea071a5d0d84573632aa835d3240e87c3b99b20537e049/detection/f-01678a1d46c240b2e2ea071a5d0d84573632aa835d3240e87c3b99b20537e049-1593262246), so its probably going to reflect on klink too.

**Comment by pauby** [comment]
@majkinetor 

> Thank you. I think we ca now safely close this. I will add note on package.

Make sure you reference the official source for the notes on the AV detections.
