### ISSUE TITLE
(Firefox) List/Upgrade fails when package does not include SemVer patch version

### ISSUE THREAD

**Issue by mwtrigg** [chocolatey-community/chocolatey-coreteampackages#1581]
http://disq.us/p/2dfyljl <- details on the problem.

## Expected Behavior
Repository containing Firefox version 82.0, 82.0.1, 82.0.2, 82.0.3, 83.0; version 82.0.3 currently installed on local machine
`choco list Firefox` should produce the following results:
`Firefox 83.0`

`choco upgrade Firefox` should produce the following results:
`You have Firefox v82.0.3 installed. Version 83.0 is available based on your source(s)`

## Current Behavior
`choco list Firefox` actually produces the following:
`Firefox 82.0.3`

`choco upgrade Firefox` actually produces the following:
`Firefox v82.0.3 is the latest version available based on your source(s).`

`choco list Firefox --all-versions`
`Firefox 82.0.3`
`Firefox 82.0.2`
`Firefox 82.0.1`
`Firefox 81.0.2`
`Firefox 83.0`
`Firefox 82.0`
`Firefox 81.0`

## Possible Solution
1. Either ensure that when generating the package the patch version (0) is always included when a new major version is released, or
2. Figure out _why_ this appears to happen - I've only ever seen this on Firefox.

## Steps to Reproduce (for bugs)
1. `choco install Firefox --version=82.0.3`
2. `choco upgrade` (when version 83.0 is available in the source)

## Your Environment
* Package Version used: 82.0.3
* Operating System and version: Windows 10 2004
* Chocolatey version: 10.15

**Comment by gep13** [comment]
@mwtrigg I do not believe that this is an issue with the version numbers.  The reason that I make this assertion is that to Chocolatey, `83.0` is the same as `83.0.0`, so having the extra patch version number in there is _not_ a requirement.

On my machine, I specifically installed version 82.0.3 of Firefox, and I have just run the following command:

```
choco upgrade firefox
```

The result is the following:

![image](https://user-images.githubusercontent.com/1271146/100325358-6898c200-2fc0-11eb-929f-8a03f5699dc1.png)

Which is exactly as expected.

My gut feeling is that this is a problem with the additional sources that you have configured, and perhaps the priority that is assigned to those sources.  The end result being that you aren't being told what the highest available version is, due to the Chocolatey configuration that you have in place.

I don't believe that this is the correct place for this issue, since the package itself is working as expected.
