### ISSUE TITLE
(spotify) Error - hashes do not match.

### ISSUE THREAD

**Issue by FreezyLemon** [chocolatey-community/chocolatey-coreteampackages#1599]
`choco install -y spotify` in a fresh Windows 10 VM.

## Expected Behavior
Spotify installs silently

## Current Behavior
```
spotify v1.1.48.625 [Approved]
spotify package files install completed. Performing other installation steps.
Downloading spotify
  from 'https://download.scdn.co/SpotifySetup.exe'

Download of SpotifyFullSetup.exe (870.52 KB) completed.
Error - hashes do not match. Actual value was '2243236E6854E8CE10AE4787197879CB80292C07BE0EE755408E4086C82C1328CA316EBBDAA092219C106B6EE36DC55B7CF5D2A06842F8E6C3262C14CF361C30'.
ERROR: Checksum for 'C:\Users\Jannik\AppData\Local\Temp\chocolatey\spotify\1.1.48.625\SpotifyFullSetup.exe' did not meet '1BF2CA1C88C3AEC7AE32F98FD20384DEB405EBDC67D3C758ECA436C64569F9CA73DA0F39D861E54A6446DF3AD6290AFB15FC1E11C7E5C1ECE80CA15829B46D1A' for checksum type 'sha512'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
The install of spotify was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\spotify\tools\ChocolateyInstall.ps1'.
 See log for details.
```

Downloading the setup file manually and checking with `Get-FileHash` gives me the same SHA512, so I don't think it's a corrupt file/download.

## Your Environment

* Package Version used: latest (none specified)
* Operating System and version: Win10 20H2 19042.631 in a VM
* Chocolatey version: v0.10.15

**Comment by AdmiringWorm** [comment]
I just checked the checksum of the file I am getting on my end, and it matches the same checksum that is specified in the package.

From the looks of it, you get served an older version (most likely from an outdated cdn selected by spotify) instead of the latest version.
I am afraid that there aren't much we can do about this, unfortunately :cry:

The checksum you are getting, are the checksum for version `1.1.47.684`, and as such you could either explicitly install that version or ignore the checksum (which should be fine in this case).

**Comment by FreezyLemon** [comment]
Alright, that's fine by me. I'll just ignore the checksum in that case, Spotify updates itself pretty easily so this isn't a big problem.
Thanks!
