### ISSUE TITLE
(curl) Outdated

### ISSUE THREAD

**Issue by majkinetor** [chocolatey-community/chocolatey-coreteampackages#1615]
https://github.com/curl/curl-www/issues/93

**Comment by AdmiringWorm** [comment]
@majkinetor is this something that you have already started looking at?

Just want to make sure we don't do any duplicate effort...

**Comment by bagder** [comment]
Also:
1. the curl website has changed domain and is now officially at `https://curl.se/` (the old one redirects)
2. the curl copyright year range in `automatic/curl/curl.nuspec` is out of date (says `1996 - 2017`)
3. the list of supported protocols miss SMBS and if you upgrade to the latest curl version, MQTT and GOPHERS...

**Comment by majkinetor** [comment]
@AdmiringWorm , No, not working on this ATM.

**Comment by AdmiringWorm** [comment]
@majkinetor got it, is this something you want to look at yourself?
Otherwise I am thinking of at least start working on getting the updater working again and targeting the official binary.

@bagder thank you for the information, I will keep that in mind when working on updating the package.

> the list of supported protocols miss SMBS and if you upgrade to the latest curl version, MQTT and GOPHERS...

I'll be honest, it isn't really my department so I don't know much about those. But considering it is still the official binary, it should in theory be fine even though those are missing (if I understood you correctly).

**Comment by AdmiringWorm** [comment]
Our updater and the metadata have been updated, just need to do some verification before pushing anything up to the repository.

**Comment by AdmiringWorm** [comment]
A new version of the package has been pushed to chocolatey, and should be available for normal consumption when it is done with the automated moderation (usually a few hours).
