### ISSUE TITLE
(freecad) no shims are created

### ISSUE THREAD

**Issue by adrianinsaval** [chocolatey-community/chocolatey-coreteampackages#1616]
Currently, no shims are created for the freecad package, I believe at least freecad.exe and freecadcmd.exe should have a shim and it seems the intent was to create a shim for freecad.exe however this doesn't work. I think this line:
https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/97aff7800036e15fd6ccb2b842b849f8b053fe5a/automatic/freecad/tools/chocolateyInstall.ps1#L27
should be changed to:
```powershell
$files = get-childitem $pp.WorkingDirectory -Exclude ($packageArgs.softwareName + "*") -include *.exe -recurse
```

**Comment by RedBaron2** [comment]
@adrianinsaval 
Apparently that line of code does too good a job. It creates `freecad.exe.ignore` which it shouldn't make at all. 

@AdmiringWorm or @majkinetor could you test to find out what is happening with this package? 

@adrianinsaval thanks for bringing this issue up.

**Comment by AdmiringWorm** [comment]
All executables have the `.ignore` file attached to them, which explicitly prevents a shim from automatically being created for them.

This is something that was added here: https://github.com/chocolatey-community/chocolatey-coreteampackages/blame/d7a465420d259cf714bd5f88385b455fa776c45d/automatic/freecad/tools/chocolateyInstall.ps1#L54, but I do not know/remember the circumstances behind that addition (the exclude argument used is not correct due to it ignoring the file extension, at a minimum the exclude argument should have been `($packageArgs.softwareName + ".exe")` at a minimum if I remember correcly).

I got nothing against changing it to allow shims for `freecad.exe` and `freecadcmd.exe` though.

**Comment by adrianinsaval** [comment]
Should I make a PR with the line I said?

**Comment by AdmiringWorm** [comment]
@adrianinsaval is it only the `freecad.exe` and `frecadcmd.exe` files that would have been matched by that line (there are no other executables that matches the globbing pattern?).

If so, then yeah, go ahead and open a pull request if you want.

**Comment by RedBaron2** [comment]
Pull Request is open and has been for a month. It directly fixes this issue, and also fixes another issue about blank variables in the chocolateyinstall file.
This is just a update.

**Comment by pauby** [comment]
The PR was closed without being merged.

**Comment by pauby** [comment]
Based on the PR being merged, I'm going to close this.
