### ISSUE TITLE
Cannot uninstall python 3.6

### ISSUE THREAD

**Issue by PhilippSelenium** [chocolatey-community/chocolatey-coreteampackages#1632]
## Steps to Reproduce (for bugs)
1. Try to uninstall an existing python 3.6 install using chocolatey 
```
C:\\ProgramData\\chocolatey\\bin\\choco.exe uninstall python3 --yes --no-progress --limit-output --package-params /InstallDir:C:\\Python36 --timeout 2700 --allow-multiple --version 3.6.8
```

act:
```
python3;/InstallDir:C:\\Python36

python3 v3.6.8
Directory 'C:\ProgramData\chocolatey\lib\python3.3.6.8.3.6.8' does not exist.
python3 uninstall not successful.
Package install not found:'C:\ProgramData\chocolatey\lib\python3.3.6.8.3.6.8'
python3 not uninstalled. An error occurred during uninstall:
 python3 uninstall not successful.

Chocolatey uninstalled 0/0 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Second path fragment must not be a drive or UNC name.
Parameter name: path2
```
exp: Uninstalls python 3.6

Note: The path that exists is C:\ProgramData\chocolatey\lib\python3 and not C:\ProgramData\chocolatey\lib\python3.3.6.8.3.6.8

## Your Environment
* Operating System and version: win 10
* Chocolatey version: 0.10.15

**Comment by AdmiringWorm** [comment]
Not sure where the problems that you are seeing are. However, I can unfortunately say it isn't a package related problem.
The messages you are seeing are from the chocolatey executable itself, saying it can't find the path and not something we can control in the package (the package itself don't even have an uninstall script).

It looks like the problem may be because you are using `--allow-multiple` when calling chocolatey uninstall, which I guess makes Chocolatey look for a package that has been side-loaded.
Anyhow, as this problem is more related to the chocolatey executable, the issue needs to be opened up over at https://github.com/chocolatey/choco (if a similar issue for the problem don't already exist).

**Comment by PhilippSelenium** [comment]
Thanks, it works when ommiting the ```--allow-multiple``` but then I still get an error saying 
```
        "Chocolatey uninstalled 0/0 packages. ",
        " See the log for details (C:\\ProgramData\\chocolatey\\logs\\chocolatey.log).",
        "Second path fragment must not be a drive or UNC name.",
        "Parameter name: path2"
```
But I will put that on top of the ~ 700 other issues you mentioned ;)
