### ISSUE TITLE
(python3/php) python3 and php conflict due to depending on different vcredist versions

### ISSUE THREAD

**Issue by mastacheata** [chocolatey-community/chocolatey-coreteampackages#1709]
## Expected Behavior

I expect that python3 and php can happily coexist when installed from chocolatey.
More technical: I expect python3 to use vcredist140 as a dependency instead of vcredist2015 (the other way around: PHP uses vcredist2015 instead of vcredist140 would be fine for me as well)

## Current Behavior

python3 fails to upgrade due to a conflict. Python3 wants to downgrade vcredist140 to ` 14.26.28720.3` , but the PHP package doesn't declare itself compatible to that

## Possible Solution

Use the same dependency in both packages. Whether that be vcredist140 for python3 or vcredist2015 for php is up to you.

## Steps to Reproduce (for bugs)

1.  Install `php` via chocolatey
2. End up with vcredist140 version ` 14.29.30037`
3. Try to install python3
4. BOOM!

## Your Environment

* Package Version used: python3 3.9.7, php 8.0.10
* Operating System and version: Windows 11 21H2
* Chocolatey version: 0.10.15
* Install/uninstall gist: https://gist.github.com/mastacheata/4ffbbc7211f3a6f1d88d9ddd21691e48

**Comment by majkinetor** [comment]
```
cinst php
cinst python -i
"BOOM!"
```

**Comment by mastacheata** [comment]
Thanks for the hint, that does get around the problem indeed.

That's a workaround, but not a fix, though.  
Is the underlying issue unfixable (i.e. php doesn't work with newer vcredist version) or did you just look for a fix that doesn't require changing anything?

**Comment by majkinetor** [comment]
I looked for a fix that doesn't change anything. The problem is specific to your usecase. 

> Is the underlying issue unfixable

In general case its IMO unfixable. In this case, its probably fixable - I essentially made python use php's vcredist (you could also go the other way around). This solution used the fact that python doesn't have any other dependencies so simple `-i` would suffice. If it depended on something else, it would require manual cinst of those. 

Definite answer in each case depends on apps involved and more serious testing - I just tried if apps start but who knows what could break. In this case probably scanning original tool sites for answers is best idea.

CBB to look it up, but choco does support parallel packages in general, so you might look into that too. This was just quickest way to solve your problem.
